# -*- coding: utf-8 -*-
"""
Single source of truth for district spoken forms.

Keys MUST match app/src/main/assets/districts.json exactly -- three of the old
Tamil Nadu keys did not ("Nilgiris" vs "The Nilgiris", "Tirupattur" vs
"Tirupathur", "Villupuram" vs "Viluppuram") and those three districts silently
had no aliases at all. gen_district_aliases.py asserts the key set now.

Each district carries:
  * its name in the script of its own state's language (the case that matters
    -- a Telugu speaker in Andhra says Telugu district names), and
  * the old or colloquial English name where one is still in common use
    (Bangalore, Bellary, Trivandrum, Calicut, Allahabad, Vizag, ...), which is
    what people actually say and what a recogniser tends to return.

Devanagari is added for the Tamil Nadu set only, where it already existed.
"""

ALIASES: dict[str, list[str]] = {

    # ── Tamil Nadu (38) ────────────────────────────────────────────────────
    "Ariyalur": ["அரியலூர்", "अरियलूर"],
    "Chengalpattu": ["செங்கல்பட்டு", "chengalpet", "चेंगलपट्टू"],
    "Chennai": ["சென்னை", "चेन्नई", "madras", "చెన్నై", "ಚೆನ್ನೈ", "ചെന്നൈ"],
    "Coimbatore": ["கோயம்புத்தூர்", "कोयंबटूर", "kovai", "கோவை", "కోయంబత్తూరు", "ಕೊಯಮತ್ತೂರು"],
    "Cuddalore": ["கடலூர்", "कुड्डालोर"],
    "Dharmapuri": ["தர்மபுரி", "धर्मपुरी"],
    "Dindigul": ["திண்டுக்கல்", "डिंडीगुल"],
    "Erode": ["ஈரோடு", "इरोड", "ఈరోడ్", "ಈರೋಡ್"],
    "Kallakurichi": ["கள்ளக்குறிச்சி", "कल्लाकुरिची"],
    "Kancheepuram": ["காஞ்சிபுரம்", "कांचीपुरम", "kanchipuram"],
    "Kanniyakumari": ["கன்னியாகுமரி", "कन्याकुमारी", "kanyakumari", "nagercoil"],
    "Karur": ["கரூர்", "करूर"],
    "Krishnagiri": ["கிருஷ்ணகிரி", "कृष्णागिरी"],
    "Madurai": ["மதுரை", "मदुरै", "మదురై", "ಮಧುರೈ", "മധുര"],
    "Mayiladuthurai": ["மயிலாடுதுறை", "मयिलादुथुरै"],
    "Nagapattinam": ["நாகப்பட்டினம்", "नागपट्टिनम"],
    "Namakkal": ["நாமக்கல்", "नामक्कल"],
    "Perambalur": ["பெரம்பலூர்", "पेरम्बलूर"],
    "Pudukkottai": ["புதுக்கோட்டை", "पुदुक्कोट्टई"],
    "Ramanathapuram": ["இராமநாதபுரம்", "रामनाथपुरम", "ramnad"],
    "Ranipet": ["இராணிப்பேட்டை", "रानीपेट"],
    "Salem": ["சேலம்", "सेलम", "సేలం", "ಸೇಲಂ"],
    "Sivaganga": ["சிவகங்கை", "शिवगंगा", "sivagangai"],
    "Tenkasi": ["தென்காசி", "तेनकासी"],
    "Thanjavur": ["தஞ்சாவூர்", "तंजावुर", "tanjore"],
    "The Nilgiris": ["நீலகிரி", "नीलगिरी", "nilgiris", "ooty", "உதகமண்டலம்", "udhagamandalam"],
    "Theni": ["தேனி", "थेनी"],
    "Thoothukudi": ["தூத்துக்குடி", "तूतुकुडी", "tuticorin"],
    "Tiruchirappalli": ["திருச்சிராப்பள்ளி", "तिरुचिरापल्ली", "trichy", "திருச்சி"],
    "Tirunelveli": ["திருநெல்வேலி", "तिरुनेलवेली", "nellai"],
    "Tirupathur": ["திருப்பத்தூர்", "तिरुपत्तूर", "tirupattur"],
    "Tiruppur": ["திருப்பூர்", "तिरुपुर", "tirupur"],
    "Tiruvallur": ["திருவள்ளூர்", "तिरुवल्लूर"],
    "Tiruvannamalai": ["திருவண்ணாமலை", "तिरुवन्नामलै"],
    "Tiruvarur": ["திருவாரூர்", "तिरुवारूर"],
    "Vellore": ["வேலூர்", "वेल्लोर"],
    "Viluppuram": ["விழுப்புரம்", "विलुप्पुरम", "villupuram"],
    "Virudhunagar": ["விருதுநகர்", "विरुधुनगर"],

    # ── Kerala (14) ────────────────────────────────────────────────────────
    "Alappuzha": ["ആലപ്പുഴ", "alleppey"],
    "Ernakulam": ["എറണാകുളം", "kochi", "cochin", "കൊച്ചി"],
    "Idukki": ["ഇടുക്കി"],
    "Kannur": ["കണ്ണൂർ", "cannanore"],
    "Kasaragod": ["കാസർഗോഡ്", "kasargod", "kasaragode"],
    "Kollam": ["കൊല്ലം", "quilon"],
    "Kottayam": ["കോട്ടയം"],
    "Kozhikode": ["കോഴിക്കോട്", "calicut"],
    "Malappuram": ["മലപ്പുറം"],
    "Palakkad": ["പാലക്കാട്", "palghat"],
    "Pathanamthitta": ["പത്തനംതിട്ട"],
    "Thiruvananthapuram": ["തിരുവനന്തപുരം", "trivandrum"],
    "Thrissur": ["തൃശ്ശൂർ", "trichur", "തൃശൂർ"],
    "Wayanad": ["വയനാട്", "kalpetta"],

    # ── Karnataka (31) ─────────────────────────────────────────────────────
    "Bagalkot": ["ಬಾಗಲಕೋಟೆ", "bagalkote"],
    "Ballari": ["ಬಳ್ಳಾರಿ", "bellary"],
    "Belagavi": ["ಬೆಳಗಾವಿ", "belgaum"],
    "Bengaluru Rural": ["ಬೆಂಗಳೂರು ಗ್ರಾಮಾಂತರ", "bangalore rural"],
    "Bengaluru Urban": ["ಬೆಂಗಳೂರು ನಗರ", "ಬೆಂಗಳೂರು", "bangalore", "bengaluru"],
    "Bidar": ["ಬೀದರ್"],
    "Chamarajanagar": ["ಚಾಮರಾಜನಗರ"],
    "Chikkaballapur": ["ಚಿಕ್ಕಬಳ್ಳಾಪುರ", "chikballapur"],
    "Chikkamagaluru": ["ಚಿಕ್ಕಮಗಳೂರು", "chikmagalur"],
    "Chitradurga": ["ಚಿತ್ರದುರ್ಗ"],
    "Dakshina Kannada": ["ದಕ್ಷಿಣ ಕನ್ನಡ", "mangalore", "mangaluru", "ಮಂಗಳೂರು"],
    "Davanagere": ["ದಾವಣಗೆರೆ", "davangere"],
    "Dharwad": ["ಧಾರವಾಡ", "hubli", "ಹುಬ್ಬಳ್ಳಿ", "hubballi"],
    "Gadag": ["ಗದಗ"],
    "Hassan": ["ಹಾಸನ"],
    "Haveri": ["ಹಾವೇರಿ"],
    "Kalaburagi": ["ಕಲಬುರಗಿ", "gulbarga"],
    "Kodagu": ["ಕೊಡಗು", "coorg", "madikeri"],
    "Kolar": ["ಕೋಲಾರ"],
    "Koppal": ["ಕೊಪ್ಪಳ"],
    "Mandya": ["ಮಂಡ್ಯ"],
    "Mysuru": ["ಮೈಸೂರು", "mysore"],
    "Raichur": ["ರಾಯಚೂರು"],
    "Ramanagara": ["ರಾಮನಗರ"],
    "Shivamogga": ["ಶಿವಮೊಗ್ಗ", "shimoga"],
    "Tumakuru": ["ತುಮಕೂರು", "tumkur"],
    "Udupi": ["ಉಡುಪಿ"],
    "Uttara Kannada": ["ಉತ್ತರ ಕನ್ನಡ", "karwar", "ಕಾರವಾರ"],
    "Vijayanagara": ["ವಿಜಯನಗರ", "hosapete", "hospet"],
    "Vijayapura": ["ವಿಜಯಪುರ", "bijapur"],
    "Yadgir": ["ಯಾದಗಿರಿ", "yadgiri"],

    # ── Andhra Pradesh (29) ────────────────────────────────────────────────
    "Alluri Sitharama Raju": ["అల్లూరి సీతారామరాజు", "alluri", "paderu"],
    "Anakapalli": ["అనకాపల్లి", "anakapalle"],
    "Anantapur": ["అనంతపురం", "anantapuramu", "ananthapuram"],
    "Annamayya": ["అన్నమయ్య", "rayachoti", "మదనపల్లె", "madanapalli"],
    "Bapatla": ["బాపట్ల"],
    "Chittoor": ["చిత్తూరు", "chittor"],
    "Dr. B.R. Ambedkar Konaseema": ["కోనసీమ", "konaseema", "amalapuram"],
    "East Godavari": ["తూర్పు గోదావరి", "rajahmundry", "rajamahendravaram"],
    "Eluru": ["ఏలూరు"],
    "Guntur": ["గుంటూరు"],
    "Kakinada": ["కాకినాడ"],
    "Krishna": ["కృష్ణా", "machilipatnam", "bandar"],
    "Kurnool": ["కర్నూలు", "kurnoolu"],
    "Markapuram": ["మార్కాపురం", "markapur"],
    "NTR": ["ఎన్టీఆర్", "vijayawada", "విజయవాడ"],
    "Nandyal": ["నంద్యాల", "nandyala"],
    "Palnadu": ["పల్నాడు", "narasaraopet"],
    "Parvathipuram Manyam": ["పార్వతీపురం మన్యం", "parvathipuram"],
    "Polavaram": ["పోలవరం"],
    "Prakasam": ["ప్రకాశం", "ongole"],
    "Sri Potti Sriramulu Nellore": ["నెల్లూరు", "nellore"],
    "Sri Sathya Sai": ["శ్రీ సత్యసాయి", "puttaparthi", "sathya sai"],
    "Srikakulam": ["శ్రీకాకుళం"],
    "Tirupati": ["తిరుపతి"],
    "Visakhapatnam": ["విశాఖపట్నం", "vizag", "vishakhapatnam"],
    "Vizianagaram": ["విజయనగరం", "vijayanagaram"],
    "West Godavari": ["పశ్చిమ గోదావరి", "bhimavaram"],
    "YSR Kadapa": ["కడప", "kadapa", "cuddapah", "ysr"],

    # ── Uttar Pradesh (75) ─────────────────────────────────────────────────
    "Agra": ["आगरा"],
    "Aligarh": ["अलीगढ़"],
    "Ambedkar Nagar": ["अम्बेडकर नगर", "akbarpur", "ambedkarnagar"],
    "Amethi": ["अमेठी"],
    "Amroha": ["अमरोहा"],
    "Auraiya": ["औरैया"],
    "Ayodhya": ["अयोध्या", "faizabad"],
    "Azamgarh": ["आजमगढ़"],
    "Baghpat": ["बागपत", "bagpat"],
    "Bahraich": ["बहराइच"],
    "Ballia": ["बलिया"],
    "Balrampur": ["बलरामपुर"],
    "Banda": ["बांदा"],
    "Barabanki": ["बाराबंकी"],
    "Bareilly": ["बरेली"],
    "Basti": ["बस्ती"],
    "Bhadohi": ["भदोही", "sant ravidas nagar"],
    "Bijnor": ["बिजनौर"],
    "Budaun": ["बदायूँ", "badaun"],
    "Bulandshahr": ["बुलंदशहर"],
    "Chandauli": ["चंदौली"],
    "Chitrakoot": ["चित्रकूट"],
    "Deoria": ["देवरिया"],
    "Etah": ["एटा"],
    "Etawah": ["इटावा"],
    "Farrukhabad": ["फर्रुखाबाद", "fatehgarh"],
    "Fatehpur": ["फतेहपुर"],
    "Firozabad": ["फिरोजाबाद"],
    "Gautam Buddha Nagar": ["गौतम बुद्ध नगर", "noida", "greater noida"],
    "Ghaziabad": ["गाजियाबाद"],
    "Ghazipur": ["गाजीपुर"],
    "Gonda": ["गोंडा"],
    "Gorakhpur": ["गोरखपुर"],
    "Hamirpur": ["हमीरपुर"],
    "Hapur": ["हापुड़"],
    "Hardoi": ["हरदोई"],
    "Hathras": ["हाथरस"],
    "Jalaun": ["जालौन", "orai"],
    "Jaunpur": ["जौनपुर"],
    "Jhansi": ["झांसी"],
    "Kannauj": ["कन्नौज"],
    "Kanpur Dehat": ["कानपुर देहात", "akbarpur maati"],
    "Kanpur Nagar": ["कानपुर", "kanpur"],
    "Kasganj": ["कासगंज"],
    "Kaushambi": ["कौशाम्बी", "manjhanpur"],
    "Kushinagar": ["कुशीनगर", "padrauna"],
    "Lakhimpur Kheri": ["लखीमपुर खीरी", "kheri", "lakhimpur"],
    "Lalitpur": ["ललितपुर"],
    "Lucknow": ["लखनऊ"],
    "Maharajganj": ["महराजगंज", "mahrajganj"],
    "Mahoba": ["महोबा"],
    "Mainpuri": ["मैनपुरी"],
    "Mathura": ["मथुरा"],
    "Mau": ["मऊ", "maunath bhanjan"],
    "Meerut": ["मेरठ"],
    "Mirzapur": ["मिर्जापुर"],
    "Moradabad": ["मुरादाबाद"],
    "Muzaffarnagar": ["मुजफ्फरनगर"],
    "Pilibhit": ["पीलीभीत"],
    "Pratapgarh": ["प्रतापगढ़"],
    "Prayagraj": ["प्रयागराज", "allahabad", "इलाहाबाद"],
    "Raebareli": ["रायबरेली", "rae bareli"],
    "Rampur": ["रामपुर"],
    "Saharanpur": ["सहारनपुर"],
    "Sambhal": ["संभल", "bhim nagar"],
    "Sant Kabir Nagar": ["संत कबीर नगर", "khalilabad"],
    "Shahjahanpur": ["शाहजहाँपुर"],
    "Shamli": ["शामली"],
    "Shravasti": ["श्रावस्ती", "bhinga"],
    "Siddharthnagar": ["सिद्धार्थनगर", "siddharth nagar", "navgarh"],
    "Sitapur": ["सीतापुर"],
    "Sonbhadra": ["सोनभद्र", "robertsganj"],
    "Sultanpur": ["सुल्तानपुर"],
    "Unnao": ["उन्नाव"],
    "Varanasi": ["वाराणसी", "banaras", "benares", "काशी", "kashi"],
}
